routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Auth\LoginController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index')->name('home');
Route::get('/posts/{id}', 'HomeController@showpost')->name('home.post');
Route::get('/postdetails/{id}', 'HomeController@postdetails')->name('home.postdetails');
Route::get('/test', 'HomeController@test')->name('home.test');

Route::get('/search', 'SearchController@search')->name('search');

Auth::routes();

//for admin authentication
//Route::get('admin/home', 'AdminLoginController@index');
Route::get('adminlogin', 'Adminlogin\LoginController@showLoginForm')->name('admin.login');
Route::post('adminlogin', 'AdminLogin\LoginController@login');
Route::post('admin-password/email', 'AdminLogin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
Route::get('admin-password/reset', 'AdminLogin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
Route::post('admin-password/reset', 'AdminLogin\ResetPasswordController@reset')->name('admin.password.reset');
Route::get('admin-password/reset/{token}', 'AdminLogin\ResetPasswordController@showResetForm')->name('admin.password.reset');






Route::group(['middleware'=>['auth']],function(){
    Route::post('favorite/{post}/add','FavoriteController@add')->name('post.favorite');
    Route::post('comment/{post}','CommentController@store')->name('comment.store');

});


Route::group(['as'=>'admin.','prefix'=>'admin', 'namespace'=>'Admin', 'middleware'=>['auth:admin',]], function(){
    Route::get('dashboard','DashboardController@index')->name('dashboard');
    Route::resource('roles','RoleController');
    Route::resource('users','UserController');
    Route::resource('tags','TagController');
    Route::resource('categories','CategoryController');
    Route::resource('posts','PostController');

    Route::get('/pending/post','PostController@pending')->name('post.pending');
    Route::put('/post/{id}/approve','PostController@approval')->name('post.approve');

    Route::get('/subscriber','SubscriberController@index')->name('subscriber.index');
    Route::delete('/subscriber/{subscriber}','SubscriberController@destroy')->name('subscriber.destroy');

    Route::get('/favorite','FavoriteController@index')->name('favorite.index');

    Route::get('/comments','CommentController@index')->name('comment.index');
    Route::delete('/comments/{id}','CommentController@destroy')->name('comment.destroy');

});

Route::group(['as'=>'author.','prefix'=>'author','namespace'=>'Author','middleware'=>['auth']],function(){
    Route::get('dashboard','DashboardController@index')->name('dashboard');
    Route::resource('users','UserController');
    Route::resource('posts','PostController');

    Route::get('/favorite','FavoriteController@index')->name('favorite.index');

    Route::get('/comments','CommentController@index')->name('comment.index');
    Route::delete('/comments/{id}','CommentController@destroy')->name('comment.destroy');

});

/*Route::group(['as'=>'user.','prefix'=>'user','namespace'=>'User','middleware'=>['auth','user']],function(){
    Route::get('dashboard','DashboardController@index')->name('dashboard');


});*/

Route::post('subscriber','SubscriberController@store')->name('subscriber.store');
Route::get('/login/{provider}', [LoginController::class, 'redirectToProvider'])->name('login.provider');
Route::get('/login/{provider}/callback', [LoginController::class, 'handleProvider'])->name('login.callback');

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;
    protected $guarded = ['id'];

    public function permissions()
    {
        return $this->belongsToMany(Permission::class);
    }

    public function admins()
    {
        return $this->hasMany(Admin::class);
    }



}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Role;
use App\Models\Module;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Auth;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Gate::authorize('admin.roles.index');
        $roles = Role::all();
        $auth = Auth::user();
        return view('admin.roles.index',compact('roles','auth'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        Gate::authorize('admin.roles.create');
        $modules = Module::all();
        return view('admin.roles.form',compact('modules'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Gate::authorize('admin.roles.create');
        $this->validate($request,[
            'name' => 'required|unique:roles',
            'permissions' => 'required|array',
            'permissions.*' => 'integer'
        ]);

        Role::create([
            'name' => $request->name,
            'slug' => Str::slug($request->name),
        ])->permissions()->sync($request->input('permissions'),[]);
        notify()->success("Role Successfully Created","Added");
        return redirect()->route('admin.roles.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \admin\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \admin\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        Gate::authorize('admin.roles.edit');
        $modules = Module::all();
        return view('admin.roles.form',compact('modules','role'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \admin\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {
        Gate::authorize('admin.roles.edit');
        $role->update([
            'name' => $request->name,
            'slug' => Str::slug($request->name)
        ]);
        $role->permissions()->sync($request->input('permissions'));
        notify()->success("Role Successfully Updated","Updated");
        return redirect()->route('admin.roles.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \admin\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        Gate::authorize('admin.roles.destroy');
        if($role->deletable)
        {
            $role->delete();
            notify()->success("Role Successfully Deleted","Delete");
        }

        else
        {
            notify()->error("You can not delete this","Error","topLeft");
        }
        return back();
    }
}

resources/views/admin/roles/form.blade.php
@extends('layouts.backend.app')

@section('title','Roles')

@push('css')

@endpush



@section('content')


<div class="container-fluid">

    <!-- Vertical Layout | With Floating Label -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        <div>{{ isset($role) ? 'Edit ' : 'Create '}}Roles</div>
                    </h2>

                </div>
                <div class="body">
                    <form method="POST" action="{{isset($role) ? route('admin.roles.update',$role->id) : route('admin.roles.store')}}">
                        @csrf
                        @isset($role)
                        @method('PUT')
                        @endisset
                        <div class="card-body">
                        <h5 class="card-title">Manage Roles</h5>
                        <div class="form-group">
                        <label for="name">Role Name</label>
                        <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $role->name ?? old('name') }}"  autofocus>

                                   @error('name')
                                       <span class="invalid-feedback" role="alert">
                                           <strong>{{ $message }}</strong>
                                       </span>
                                   @enderror

                          </div>

                          <div class="text-center"><strong>Manage Permission For Role</strong>
                                   @error('permissions')
                                       <span class="text-danger" role="alert">
                                           <strong>{{ $message }}</strong>
                                       </span>
                                   @enderror
                                   </div>

                        <div class="form-group">
                            <div class="custom-control custom-checkbox">
                            <input type="checkbox" class="custom-control-input"
                             id="select-all">
                             <label for="select-all" class="custom-control-label">Select All</label>
                            </div>
                            </div>

                         @forelse($modules->chunk(3) as $key=>$chunks)
                           <div class="form-row">
                           @foreach($chunks as $key=>$module)
                           <div class="col">
                           <h5>Module : {{ $module->name}}</h5>
                           @foreach($module->permissions as $key=> $permission)
                           <div class="mb-3 ml-4">
                           <div class="custom-control custom-checkbox mb-2">
                             <input type="checkbox" class="custom-control-input"
                             id="permission-{{$permission->id}}"
                             name="permissions[]" value="{{$permission->id}}"
                             @isset($role)
                             @foreach($role->permissions as $rpermission)
                             {{$permission->id == $rpermission->id ? 'checked' : ''}}
                             @endforeach
                             @endisset
                             >
                             <label for="permission-{{$permission->id}}" class="custom-control-label">{{$permission->name}}</label>
                           </div>
                           </div>
                           @endforeach
                           </div>
                           @endforeach
                           </div>
                         @empty
                         <div class="row">
                         <div class="col text-center">
                         <strong>No Module Found.</strong>
                         </div>
                         </div>
                         @endforelse


                        <a type="button" class="btn btn-danger m-t-15 waves-effect" href="{{ route('admin.roles.index') }}">BACK</a>
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">
                            @isset($role)
                            Update
                            @else
                            Create
                            @endisset
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Vertical Layout | With Floating Label -->

</div>

@endsection

@push('js')
<script>
   $('#select-all').click(function(event){
       if(this.checked)
       {
           $(':checkbox').each(function(){
               this.checked = true;
           });
       }
       else
       {
           $(':checkbox').each(function(){
               this.checked = false;
           });
       }
   });
</script>
@endpush

resources/views/admin/roles/index.blade.php
@extends('layouts.backend.app')

@section('title','Roles')

@push('css')

@endpush

@section('content')

<div class="container-fluid">
    <div class="block-header">
        @if($auth->hasPermission('admin.roles.create'))
      <a class="btn btn-primary waves effect" href="{{ route('admin.roles.create') }}">
      <li class="material-icons">add</li>
      <span>Add New Role</span>
      </a>
      @endif
    </div>

    <!-- Exportable Table -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        All Roles
                        <span class="badge bg-blue">{{$roles->count()}}</span>
                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="javascript:void(0);">Action</a></li>
                                <li><a href="javascript:void(0);">Another action</a></li>
                                <li><a href="javascript:void(0);">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Permissions</th>
                                    <th>Updated At</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                         <tbody>
                         @foreach($roles as $key=>$role)
                         <tr>
                         <td>{{$role->name}}</td>
                         <td>
                            @if($role->permissions->count() > 0 )
                            <span class="badge badge-info">{{$role->permissions->count()}}</span>
                            @else
                            <span class="badge badge-danger">No Permission Found :(</span>
                            @endif
                         </td>
                         <td>{{$role->updated_at->diffForHumans()}}</td>
                         @if($auth->hasPermission('admin.roles.edit'))
                         <td class="text-center">
                         <a href="{{route('admin.roles.edit',$role->id)}}" class="btn btn-info waves-effect">
                         <i class="material-icons">edit</i>
                         </a>
                         @endif

                         @if($auth->hasPermission('admin.roles.destroy'))
                         <button class="btn btn-danger waves effect" type="button"
                         onclick="deleterole({{$role->id}})">
                         <li class="material-icons">delete</li>
                         </button>
                         <form id="deleteform-{{$role->id}}" action="{{route('admin.roles.destroy',$role->id)}}" method="POST" style="display: none;">
                         @csrf
                        @method('DELETE')
                        @endif
                        </form>
                         </td>
                         </tr>
                         @endforeach


                         </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Exportable Table -->
</div>

@endsection

<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script type="text/javascript">
    function deleterole(id)
    {
        Swal.fire({
  title: 'Are you sure?',
  text: "You won't be able to revert this!",
  icon: 'warning',
  showCancelButton: true,
  confirmButtonColor: '#3085d6',
  cancelButtonColor: '#d33',
  confirmButtonText: 'Yes, delete it!'
}).then((result) => {
  if (result.isConfirmed) {
   event.preventDefault();
   document.getElementById('deleteform-'+id).submit();
  }
})
    }
    </script>


@push('js')

@endpush