routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Auth\LoginController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index')->name('home');
Route::get('/posts/{id}', 'HomeController@showpost')->name('home.post');
Route::get('/postdetails/{id}', 'HomeController@postdetails')->name('home.postdetails');
Route::get('/test', 'HomeController@test')->name('home.test');

Route::get('/search', 'SearchController@search')->name('search');

Auth::routes();

//for admin authentication
//Route::get('admin/home', 'AdminLoginController@index');
Route::get('adminlogin', 'Adminlogin\LoginController@showLoginForm')->name('admin.login');
Route::post('adminlogin', 'AdminLogin\LoginController@login');
Route::post('admin-password/email', 'AdminLogin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
Route::get('admin-password/reset', 'AdminLogin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
Route::post('admin-password/reset', 'AdminLogin\ResetPasswordController@reset')->name('admin.password.reset');
Route::get('admin-password/reset/{token}', 'AdminLogin\ResetPasswordController@showResetForm')->name('admin.password.reset');






Route::group(['middleware'=>['auth']],function(){
    Route::post('favorite/{post}/add','FavoriteController@add')->name('post.favorite');
    Route::post('comment/{post}','CommentController@store')->name('comment.store');

});


Route::group(['as'=>'admin.','prefix'=>'admin', 'namespace'=>'Admin', 'middleware'=>['auth:admin',]], function(){
    Route::get('dashboard','DashboardController@index')->name('dashboard');
    Route::resource('roles','RoleController');
    Route::resource('users','UserController');
    Route::resource('tags','TagController');
    Route::resource('categories','CategoryController');
    Route::resource('posts','PostController');

    Route::get('/pending/post','PostController@pending')->name('post.pending');
    Route::put('/post/{id}/approve','PostController@approval')->name('post.approve');

    Route::get('/subscriber','SubscriberController@index')->name('subscriber.index');
    Route::delete('/subscriber/{subscriber}','SubscriberController@destroy')->name('subscriber.destroy');

    Route::get('/favorite','FavoriteController@index')->name('favorite.index');

    Route::get('/comments','CommentController@index')->name('comment.index');
    Route::delete('/comments/{id}','CommentController@destroy')->name('comment.destroy');

});

Route::group(['as'=>'author.','prefix'=>'author','namespace'=>'Author','middleware'=>['auth']],function(){
    Route::get('dashboard','DashboardController@index')->name('dashboard');
    Route::resource('users','UserController');
    Route::resource('posts','PostController');

    Route::get('/favorite','FavoriteController@index')->name('favorite.index');

    Route::get('/comments','CommentController@index')->name('comment.index');
    Route::delete('/comments/{id}','CommentController@destroy')->name('comment.destroy');

});

/*Route::group(['as'=>'user.','prefix'=>'user','namespace'=>'User','middleware'=>['auth','user']],function(){
    Route::get('dashboard','DashboardController@index')->name('dashboard');


});*/

Route::post('subscriber','SubscriberController@store')->name('subscriber.store');
Route::get('/login/{provider}', [LoginController::class, 'redirectToProvider'])->name('login.provider');
Route::get('/login/{provider}/callback', [LoginController::class, 'handleProvider'])->name('login.callback');

resources/views/layouts/backend/partial/navbar.blade.php
<!-- Top Bar -->
<nav class="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
            <a href="javascript:void(0);" class="bars"></a>
            <a class="navbar-brand" href="index.html">Shwapna Blog</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <!-- Call Search -->
                <li><a href="javascript:void(0);" class="js-search" data-close="true"><i class="material-icons">search</i></a></li>
                <!-- #END# Call Search -->

            </ul>
        </div>
    </div>
</nav>
<!-- #Top Bar -->

resources/views/layouts/backend/partial/sidebar.blade.php
<aside id="leftsidebar" class="sidebar">
    <!-- User Info -->
    <div class="user-info">
        <div class="image">
            <img src="{{ Storage::disk('public')->url('userphoto/'.Auth::user()->image) }}" width="48" height="48" alt="User" />
        </div>
        <div class="info-container">
            <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ Auth::user()->name }}</div>
            <div class="email">{{ Auth::user()->email }}</div>
            <div class="btn-group user-helper-dropdown">
                <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                <ul class="dropdown-menu pull-right">
                    <li><a href="javascript:void(0);"><i class="material-icons">person</i>Profile</a></li>
                    <li role="separator" class="divider"></li>
                    <li>


                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                             document.getElementById('logout-form').submit();">
                               <i class="material-icons">input</i>Sign Out
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>


                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- #User Info -->
    <!-- Menu -->
    <div class="menu">
        <ul class="list">
            <li class="header">MAIN NAVIGATION</li>

            @if(Request::is('admin*'))
            <li class="{{ Request::is('admin/dashboard') ? 'active' : '' }}">
                <a href="{{route('admin.dashboard')}}">
                    <i class="material-icons">dashboard</i>
                    <span>Dashboard</span>
                </a>
                </li>

                @if(Auth::user()->hasPermission('admin.roles.index'))
                <li class="{{ Request::is('admin/roles*') ? 'active' : '' }}">
                <a href="{{route('admin.roles.index')}}">
                    <i class="material-icons">label</i>
                    <span>Roles Management</span>
                </a>
                </li>
                @endif

                @if(Auth::user()->hasPermission('admin.users.index'))
                <li class="{{ Request::is('admin/users*') ? 'active' : '' }}">
                <a href="{{route('admin.users.index')}}">
                    <i class="material-icons">label</i>
                    <span>Users</span>
                </a>
                </li>
                @endif
                @if(Auth::user()->hasPermission('author.tags.index'))
                <li class="{{ Request::is('admin/tags*') ? 'active' : '' }}">
                    <a href="{{route('admin.tags.index')}}">
                        <i class="material-icons">label</i>
                        <span>Tag</span>
                    </a>
                </li>
                @endif

                @if(Auth::user()->hasPermission('author.categories.index'))
                <li class="{{ Request::is('admin/categories*') ? 'active' : '' }}">
                    <a href="{{route('admin.categories.index')}}">
                        <i class="material-icons">label</i>
                        <span>Category</span>
                    </a>
                </li>
                @endif

                @if(Auth::user()->hasPermission('author.posts.index'))
                <li class="{{ Request::is('admin/posts*') ? 'active' : '' }}">
                    <a href="{{route('admin.posts.index')}}">
                        <i class="material-icons">label</i>
                        <span>Post</span>
                    </a>
                </li>
                @endif

                @if(Auth::user()->hasPermission('author.pendings.index'))
                <li class="{{ Request::is('admin/pending/post') ? 'active' : '' }}">
                    <a href="{{route('admin.post.pending')}}">
                        <i class="material-icons">library_books</i>
                        <span>Pending Post</span>
                    </a>
                </li>
                @endif

                    <li class="{{ Request::is('admin/favorite') ? 'active' : '' }}">
                        <a href="{{route('admin.favorite.index')}}">
                            <i class="material-icons">favorite</i>
                            <span>Favorite Posts</span>
                        </a>
                    </li>

                    <li class="{{ Request::is('admin/comments') ? 'active' : '' }}">
                        <a href="{{route('admin.comment.index')}}">
                            <i class="material-icons">comment</i>
                            <span>Comments</span>
                        </a>
                    </li>

                    @if(Auth::user()->hasPermission('author.subscribers.index'))
                    <li class="{{ Request::is('admin/subscriber') ? 'active' : '' }}">
                    <a href="{{route('admin.subscriber.index')}}">
                        <i class="material-icons">subscriptions</i>
                        <span>Subscribers</span>
                    </a>
                    </li>
                    @endif

                <li class="header">System</li>
                <li class="">
                <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                             document.getElementById('logout-form').submit();">
                               <i class="material-icons">input</i>
                               <span>Log Out</span>
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                </li>
            @endif

            @if(Request::is('author*'))

            <li class="{{ Request::is('author/dashboard') ? 'active' : '' }}">
                <a href="{{route('author.dashboard')}}">
                    <i class="material-icons">dashboard</i>
                    <span>Dashboard</span>
                </a>
                </li>

               
                <li class="header">System</li>

                <li class="">
                <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                             document.getElementById('logout-form').submit();">
                               <i class="material-icons">input</i>
                               <span>Log Out</span>
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                </li>

            @endif



        </ul>
    </div>
    <!-- #Menu -->
    <!-- Footer -->
    <div class="legal">
        <div class="copyright">
            &copy; 2016 - 2017 <a href="javascript:void(0);">adminBSB - Material Design</a>.
        </div>
        <div class="version">
            <b>Version: </b> 1.0.5
        </div>
    </div>
    <!-- #Footer -->
</aside>