routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Auth\LoginController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index')->name('home');
Route::get('/posts/{id}', 'HomeController@showpost')->name('home.post');
Route::get('/postdetails/{id}', 'HomeController@postdetails')->name('home.postdetails');
Route::get('/test', 'HomeController@test')->name('home.test');

Route::get('/search', 'SearchController@search')->name('search');

Auth::routes();

//for admin authentication
//Route::get('admin/home', 'AdminLoginController@index');
Route::get('adminlogin', 'Adminlogin\LoginController@showLoginForm')->name('admin.login');
Route::post('adminlogin', 'AdminLogin\LoginController@login');
Route::post('admin-password/email', 'AdminLogin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
Route::get('admin-password/reset', 'AdminLogin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
Route::post('admin-password/reset', 'AdminLogin\ResetPasswordController@reset')->name('admin.password.reset');
Route::get('admin-password/reset/{token}', 'AdminLogin\ResetPasswordController@showResetForm')->name('admin.password.reset');






Route::group(['middleware'=>['auth']],function(){
    Route::post('favorite/{post}/add','FavoriteController@add')->name('post.favorite');
    Route::post('comment/{post}','CommentController@store')->name('comment.store');

});


Route::group(['as'=>'admin.','prefix'=>'admin', 'namespace'=>'Admin', 'middleware'=>['auth:admin',]], function(){
    Route::get('dashboard','DashboardController@index')->name('dashboard');
    Route::resource('roles','RoleController');
    Route::resource('users','UserController');
    Route::resource('tags','TagController');
    Route::resource('categories','CategoryController');
    Route::resource('posts','PostController');

    Route::get('/pending/post','PostController@pending')->name('post.pending');
    Route::put('/post/{id}/approve','PostController@approval')->name('post.approve');

    Route::get('/subscriber','SubscriberController@index')->name('subscriber.index');
    Route::delete('/subscriber/{subscriber}','SubscriberController@destroy')->name('subscriber.destroy');

    Route::get('/favorite','FavoriteController@index')->name('favorite.index');

    Route::get('/comments','CommentController@index')->name('comment.index');
    Route::delete('/comments/{id}','CommentController@destroy')->name('comment.destroy');

});

Route::group(['as'=>'author.','prefix'=>'author','namespace'=>'Author','middleware'=>['auth']],function(){
    Route::get('dashboard','DashboardController@index')->name('dashboard');
    Route::resource('users','UserController');
    Route::resource('posts','PostController');

    Route::get('/favorite','FavoriteController@index')->name('favorite.index');

    Route::get('/comments','CommentController@index')->name('comment.index');
    Route::delete('/comments/{id}','CommentController@destroy')->name('comment.destroy');

});

/*Route::group(['as'=>'user.','prefix'=>'user','namespace'=>'User','middleware'=>['auth','user']],function(){
    Route::get('dashboard','DashboardController@index')->name('dashboard');


});*/

Route::post('subscriber','SubscriberController@store')->name('subscriber.store');
Route::get('/login/{provider}', [LoginController::class, 'redirectToProvider'])->name('login.provider');
Route::get('/login/{provider}/callback', [LoginController::class, 'handleProvider'])->name('login.callback');

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    use HasFactory;
    protected $guarded = ['id'];

    public function posts()
    {
        return $this->belongsToMany(Post::class);
    }
}

app/Http/Controllers/Admin/TagController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Gate;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Gate::authorize('author.tags.index');
        $tags = Tag::latest()->get();
        return view('admin.tags.index',compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        Gate::authorize('author.tags.create');
        return view('admin.tags.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Gate::authorize('author.tags.create');
        $this->validate($request,[
            'tagname' => 'required'
        ]);

        $tag = Tag::create([
            'name' => $request->tagname,
            'slug' => Str::slug($request->tagname),

        ]);

        notify()->success("Tag Addeed",'success');
        return redirect()->route('admin.tags.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function show(Tag $tag)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        Gate::authorize('author.tags.edit');
         return view('admin.tags.form',compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tag $tag)
    {
        Gate::authorize('author.tags.edit');
        $this->validate($request,[
            'tagname' => 'required'
        ]);
        $tag->update([
            'name' => $request->tagname,
            'slug' => Str::slug($request->tagname),

        ]);
        notify()->success("Tag Updated",'success');
        return redirect()->route('admin.tags.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        Gate::authorize('author.tags.destroy');
        $tag->delete();
        notify()->success("Tag Deleted Successfully",'success');
        return back();
    }
}

resources/views/admin/tags/form.blade.php
@extends('layouts.backend.app')

@section('title','tag')

@section('content')
<div class="container-fluid">

            <!-- Vertical Layout | With Floating Label -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                <div>{{ isset($tag) ? 'Edit ' : 'Create '}}Tags</div>
                            </h2>

                        </div>
                        <div class="body">
                            <form action="{{isset($tag) ? route('admin.tags.update',$tag->id) : route('admin.tags.store')}}" method="POST">
                                @csrf
                                @isset($tag)
                                @method('PUT')
                                @endisset
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="text" id="tagname" class="form-control @error('tagname') is-invalid @enderror" value="{{ $tag->name ?? old('name') }}" name="tagname">
                                        @error('tagname')
                                       <span class="invalid-feedback" role="alert">
                                           <strong>{{ $message }}</strong>
                                       </span>
                                       @enderror
                                        <label class="form-label">TAG NAME</label>
                                    </div>

                                </div>


                                <a type="button" class="btn btn-danger m-t-15 waves-effect" href="{{ route('admin.tags.index') }}">BACK</a>
                                <button type="submit" class="btn btn-primary m-t-15 waves-effect">
                                    @isset($tag)
                                    Update
                                    @else
                                    Create
                                    @endisset
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Vertical Layout | With Floating Label -->

        </div>
@endsection

resources/views/admin/tags/index.blade.php
@extends('layouts.backend.app')

@section('title','tag')

@push('css')
 <!-- JQuery DataTable Css -->
 <link href="{{ asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}" rel="stylesheet">
@endpush

@section('content')
<div class="container-fluid">
            <div class="block-header">
              <a class="btn btn-primary waves effect" href="{{ route('admin.tags.create') }}">
              <li class="material-icons">add</li>
              <span>Add New Tag</span>
              </a>
            </div>

            <!-- Exportable Table -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                All Tag
                                <span class="badge bg-blue">{{$tags->count()}}</span>
                            </h2>
                            <ul class="header-dropdown m-r--5">
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">more_vert</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="javascript:void(0);">Action</a></li>
                                        <li><a href="javascript:void(0);">Another action</a></li>
                                        <li><a href="javascript:void(0);">Something else here</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Name</th>
                                           <!-- <th>Post Count</th>-->
                                            <th>Created At</th>
                                            <th>Updated At</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>

                                 <tbody>
                                 @foreach($tags as $key=>$tag)
                                 <tr>
                                 <td>{{$key + 1}}</td>
                                 <td>{{$tag->name}}</td>
                                 <td>{{$tag->created_at}}</td>
                                 <td>{{$tag->updated_at}}</td>
                                 <td class="text-center">
                                 <a href="{{route('admin.tags.edit',$tag->id)}}" class="btn btn-info waves-effect">
                                 <i class="material-icons">edit</i>
                                 </a>
                                 <button class="btn btn-danger waves effect" type="button"
                                 onclick="deleteTag({{$tag->id}})">
                                 <li class="material-icons">delete</li>
                                 </button>
                                 <form id="deleteform-{{$tag->id}}" action="{{route('admin.tags.destroy',$tag->id)}}" method="POST" style="display: none;">
                                 @csrf
                                @method('DELETE')
                                </form>
                                 </td>
                                 </tr>
                                 @endforeach


                                 </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Exportable Table -->
        </div>
@endsection

@push('js')
 <!-- Jquery DataTable Plugin Js -->
 <script src="{{asset('assets/backend/plugins/jquery-datatable/jquery.dataTables.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/jszip.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js')}}"></script>
    <script src="{{asset('assets/backend/js/pages/tables/jquery-datatable.js')}}"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script type="text/javascript">
    function deleteTag(id)
    {
        Swal.fire({
  title: 'Are you sure?',
  text: "You won't be able to revert this!",
  icon: 'warning',
  showCancelButton: true,
  confirmButtonColor: '#3085d6',
  cancelButtonColor: '#d33',
  confirmButtonText: 'Yes, delete it!'
}).then((result) => {
  if (result.isConfirmed) {
   event.preventDefault();
   document.getElementById('deleteform-'+id).submit();
  }
})
    }
    </script>
@endpush